server:
  port: 8080

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/sotream
    username: sotream
    password: dS0zr52uB2f2
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 15m
      validation-query: SELECT 1
