server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sotream
    username: sotream
    password: dS0zr52uB2f2
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
